baseurl = "/"
languageCode = "en-us"
title = "GraphCMS Status"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "https://graphcms.com/assets/svg/graphcms-logo-graphql-cms.svg"
  faviconsPath = "https://graphcms.com/favicon-196x-196.png"

# List of systems monitored in this status page.
# You'll be able to change their status every time
# you open or update an incident.
# Replace these examples with your own system names.
systems = ["Simple API", "Relay API", "WebApp", "Asset CDN", "Docs", "Website"]
